name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

# https://github.com/hashicorp/setup-terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

# AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY must be set in Repo > Settings > Secrets 
# for `terraform plan` to work
#       - name: Terraform Plan
#         id: plan
#         run: terraform plan -no-color

